pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'your-creds-id', url: 'https://github.com/AnveshMannuru8/calculator.git'
            }
        }
        stage('Compile') {
            steps {
                sh 'mkdir -p out'
                sh 'javac -d out Calculator.java'
            }
        }
        stage('Run') {
            steps {
                sh 'java -cp out Calculator'
            }
        }

post {
  failure {
    emailext (
      to: 'you@example.com',
      subject: "Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
      body: "Check logs: ${env.BUILD_URL}"
    )
  }
}


    }
}

